/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Room(props) {
  const { nodes, materials } = useGLTF("/assets/room_12_18_23.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="CameraMarker"
        castShadow
        receiveShadow
        geometry={nodes.CameraMarker.geometry}
        material={materials["Material.001"]}
        position={[8.051, 2.403, 5.342]}
        scale={-0.047}
      />
      <mesh
        name="leaf"
        castShadow
        receiveShadow
        geometry={nodes.leaf.geometry}
        material={materials["Material.001"]}
        position={[-0.825, -0.174, 0.795]}
        rotation={[0.001, -0.086, -1.415]}
      />
      <mesh
        name="Cylinder"
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.001"]}
        position={[-0.492, -0.76, 0.509]}
        scale={[0.035, 0.275, 0.035]}
      />
      <mesh
        name="Desk"
        castShadow
        receiveShadow
        geometry={nodes.Desk.geometry}
        material={materials["Material.001"]}
        position={[-0.721, -0.49, -0.174]}
        scale={[0.212, 0.03, 0.407]}
      />
      <mesh
        name="Cube003"
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Material.001"]}
        position={[-0.215, -0.664, -0.193]}
        rotation={[Math.PI, -0.689, Math.PI]}
      >
        <mesh
          name="Cube004"
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials["Material.001"]}
          position={[-0.193, 0.131, -0.093]}
          scale={1.156}
        />
        <mesh
          name="Cube005"
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials["Material.001"]}
          position={[0, -0.128, 0]}
          scale={0.639}
        />
        <mesh
          name="Cube006"
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials["Material.001"]}
          position={[0, -0.158, 0]}
          scale={0.639}
        />
        <mesh
          name="Cube007"
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials["Material.001"]}
          position={[0, -0.231, 0]}
        >
          <mesh
            name="Cube009"
            castShadow
            receiveShadow
            geometry={nodes.Cube009.geometry}
            material={materials["Material.001"]}
          >
            <mesh
              name="Cube010"
              castShadow
              receiveShadow
              geometry={nodes.Cube010.geometry}
              material={materials["Material.001"]}
            />
          </mesh>
        </mesh>
        <mesh
          name="Cube012"
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={materials["Material.001"]}
          position={[-0.018, -0.067, -0.052]}
          rotation={[2.757, -0.308, 3.048]}
          scale={[-0.002, -0.005, -0.02]}
        />
        <mesh
          name="Cube013"
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials["Material.001"]}
          position={[0, -0.082, 0]}
          scale={0.639}
        />
      </mesh>
      <mesh
        name="LongWallShelf"
        castShadow
        receiveShadow
        geometry={nodes.LongWallShelf.geometry}
        material={materials["Material.001"]}
        position={[-0.981, 0.534, 0.249]}
        scale={[0.021, 0.204, 0.157]}
      />
      <mesh
        name="ShortWallShelf001"
        castShadow
        receiveShadow
        geometry={nodes.ShortWallShelf001.geometry}
        material={materials["Material.001"]}
        position={[-0.925, 0.094, -0.728]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.88, 0.873, 0.439]}
      >
        <mesh
          name="Book001"
          castShadow
          receiveShadow
          geometry={nodes.Book001.geometry}
          material={materials["Material.001"]}
          position={[0.116, 0.039, -0.022]}
          rotation={[1.572, 0.554, -3.139]}
          scale={[0.005, 0.01, 0.006]}
        />
      </mesh>
      <mesh
        name="ShortWallShelf"
        castShadow
        receiveShadow
        geometry={nodes.ShortWallShelf.geometry}
        material={materials["Material.001"]}
        position={[-0.925, 0.406, -0.728]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.88, 0.873, 0.439]}
      >
        <mesh
          name="Book002"
          castShadow
          receiveShadow
          geometry={nodes.Book002.geometry}
          material={materials["Material.001"]}
          position={[-0.093, 0.038, -0.038]}
          rotation={[-2.617, -1.57, -1.04]}
          scale={[0.003, 0.015, 0.006]}
        />
      </mesh>
      <mesh
        name="WallBoard"
        castShadow
        receiveShadow
        geometry={nodes.WallBoard.geometry}
        material={materials["Material.001"]}
        position={[-0.989, 0.223, -0.084]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.17, 0.221, 0.016]}
      />
      <mesh
        name="Cube018"
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials["Material.001"]}
        position={[-0.81, -0.184, 0.197]}
        scale={[0.123, 1.016, 1.016]}
      />
      <mesh
        name="Cube021"
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials["Material.001"]}
        position={[-0.883, -0.457, 0.212]}
        scale={[4.64, 0.099, 7.795]}
      />
      <mesh
        name="Cube025"
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials["Material.001"]}
        position={[-0.859, -0.245, -0.422]}
      />
      <mesh
        name="room"
        castShadow
        receiveShadow
        geometry={nodes.room.geometry}
        material={materials["Material.001"]}
        position={[0.695, 0.38, 3.486]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        name="room002"
        castShadow
        receiveShadow
        geometry={nodes.room002.geometry}
        material={materials["Material.001"]}
        position={[-0.07, 0.227, 1.008]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        name="Cube027"
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials["Material.001"]}
        position={[-0.07, 0.227, 0.948]}
        rotation={[0, -1.571, 0]}
        scale={[0.208, 0.205, 2.065]}
      />
      <mesh
        name="Plant_Deco_1001"
        castShadow
        receiveShadow
        geometry={nodes.Plant_Deco_1001.geometry}
        material={materials["Material.001"]}
        position={[-0.797, -0.558, 0.806]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.004}
      />
      <mesh
        name="Book_(Open)002"
        castShadow
        receiveShadow
        geometry={nodes["Book_(Open)002"].geometry}
        material={materials["Material.001"]}
        position={[-0.576, -0.445, 0.361]}
        rotation={[Math.PI / 2, 0, -2.201]}
        scale={0.004}
      />
      <mesh
        name="Cup_(Filled)002"
        castShadow
        receiveShadow
        geometry={nodes["Cup_(Filled)002"].geometry}
        material={materials["Material.001"]}
        position={[-0.627, -0.463, -0.728]}
        rotation={[Math.PI / 2, 0, -1.268]}
        scale={0.01}
      />
      <mesh
        name="Stool002"
        castShadow
        receiveShadow
        geometry={nodes.Stool002.geometry}
        material={materials["Material.001"]}
        position={[-0.747, -0.999, 0.846]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.006}
      />
      <mesh
        name="Poster_1001"
        castShadow
        receiveShadow
        geometry={nodes.Poster_1001.geometry}
        material={materials["Material.001"]}
        position={[-0.996, -0.024, 0.65]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        name="Air_Conditioner002"
        castShadow
        receiveShadow
        geometry={nodes.Air_Conditioner002.geometry}
        material={materials["Material.001"]}
        position={[-0.877, 0.912, -0.12]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.01}
      >
        <mesh
          name="Air_Conditioner_B001"
          castShadow
          receiveShadow
          geometry={nodes.Air_Conditioner_B001.geometry}
          material={materials["Material.001"]}
          position={[0, 10.52, 7.858]}
        />
      </mesh>
      <mesh
        name="Controller_(AC)001"
        castShadow
        receiveShadow
        geometry={nodes["Controller_(AC)001"].geometry}
        material={materials["Material.001"]}
        position={[-0.679, -0.549, 0.788]}
        rotation={[Math.PI / 2, 0, 2.18]}
        scale={0.007}
      />
      <mesh
        name="Pen001"
        castShadow
        receiveShadow
        geometry={nodes.Pen001.geometry}
        material={materials["Material.001"]}
        position={[-0.605, -0.46, 0.082]}
        rotation={[-Math.PI, 0.716, Math.PI / 2]}
        scale={0.01}
      />
      <mesh
        name="Smartphone_2001"
        castShadow
        receiveShadow
        geometry={nodes.Smartphone_2001.geometry}
        material={materials["Material.001"]}
        position={[-0.635, -0.456, -0.563]}
        rotation={[Math.PI / 2, 0, -1.024]}
        scale={0.01}
      />
      <mesh
        name="Plant_Deco_1002"
        castShadow
        receiveShadow
        geometry={nodes.Plant_Deco_1002.geometry}
        material={materials["Material.001"]}
        position={[-0.728, -0.558, 0.903]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.003, 0.003, 0.001]}
      />
    </group>
  );
}

useGLTF.preload("/assets/room_12_18_23.glb");
